- id: btcinr
  code: 3
  #name: BTC/EUR      # default name
  base_unit: btc
  quote_unit: inr
  #price_group_fixed: 1 # aggregate price levels in orderbook
  bid: {fee: 0, currency: inr, fixed: 2}
  ask: {fee: 0, currency: btc, fixed: 4}
  sort_order: 1
  #visible: false     # default to true
- id: ltcinr
  code: 4
  base_unit: ltc
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: ltc, fixed: 8}
- id: ltcbtc
  code: 4
  base_unit: ltc
  quote_unit: btc
  bid: {fee: 0, currency: btc, fixed: 8}
  ask: {fee: 0, currency: ltc, fixed: 8}
- id: dshinr
  code: 4
  base_unit: dsh
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: dsh, fixed: 8}
- id: bccinr
  code: 5
  base_unit: bcc
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: bcc, fixed: 8}
- id: ethinr
  code: 6
  base_unit: eth
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: eth, fixed: 8}
- id: zecinr
  code: 7
  base_unit: zec
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: zec, fixed: 8}
- id: btsinr
  code: 8
  base_unit: bts
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: bts, fixed: 8}
- id: etcinr
  code: 9
  base_unit: etc
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: etc, fixed: 8}
