- id: btcinr
  code: 3
  #name: BTC/EUR      # default name
  base_unit: btc
  quote_unit: inr
  #price_group_fixed: 1 # aggregate price levels in orderbook
  bid: {fee: 0, currency: inr, fixed: 2}
  ask: {fee: 0, currency: btc, fixed: 4}
  sort_order: 1
  #visible: false     # default to true
- id: ltcinr
  code: 4
  base_unit: ltc
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: ltc, fixed: 8}
- id: dashinr
  code: 5
  base_unit: dash
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: dash, fixed: 8}
- id: ethinr
  code: 7
  base_unit: eth
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: eth, fixed: 8}
- id: zecinr
  code: 8
  base_unit: zec
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: zec, fixed: 8}
- id: xrpinr
  code: 9
  base_unit: xrp
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: xrp, fixed: 8}
- id: ppcinr
  code: 10
  base_unit: ppc
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: ppc, fixed: 8}
- id: nmcinr
  code: 11
  base_unit: nmc
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: nmc, fixed: 8}
- id: xmrinr
  code: 12
  base_unit: xmr
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: xmr, fixed: 8}
- id: bchinr
  code: 13
  base_unit: bch
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: bch, fixed: 8}
- id: repinr
  code: 14
  base_unit: rep
  quote_unit: inr
  bid: {fee: 0, currency: inr, fixed: 8}
  ask: {fee: 0, currency: rep, fixed: 8}
- id: ltcbtc
  code: 15
  base_unit: ltc
  quote_unit: btc
  bid: {fee: 0, currency: btc, fixed: 8}
  ask: {fee: 0, currency: ltc, fixed: 8}
- id: dashbtc
  code: 29
  base_unit: dash
  quote_unit: btc
  bid: {fee: 0, currency: btc, fixed: 8}
  ask: {fee: 0, currency: dash, fixed: 8}
# - id: bccbtc
#   code: 13
#   base_unit: bcc
#   quote_unit: btc
#   bid: {fee: 0, currency: inr, fixed: 8}
#   ask: {fee: 0, currency: bcc, fixed: 8}
- id: ethbtc
  code: 30
  base_unit: eth
  quote_unit: btc
  bid: {fee: 0, currency: btc, fixed: 8}
  ask: {fee: 0, currency: eth, fixed: 8}
- id: zecbtc
  code: 31
  base_unit: zec
  quote_unit: btc
  bid: {fee: 0, currency: btc, fixed: 8}
  ask: {fee: 0, currency: zec, fixed: 8}
- id: xrpbtc
  code: 32
  base_unit: xrp
  quote_unit: btc
  bid: {fee: 0, currency: btc, fixed: 8}
  ask: {fee: 0, currency: xrp, fixed: 8}
- id: ppcbtc
  code: 33
  base_unit: ppc
  quote_unit: btc
  bid: {fee: 0, currency: btc, fixed: 8}
  ask: {fee: 0, currency: ppc, fixed: 8}
- id: nmcbtc
  code: 34
  base_unit: nmc
  quote_unit: btc
  bid: {fee: 0, currency: btc, fixed: 8}
  ask: {fee: 0, currency: nmc, fixed: 8}
- id: xmrbtc
  code: 35
  base_unit: xmr
  quote_unit: btc
  bid: {fee: 0, currency: btc, fixed: 8}
  ask: {fee: 0, currency: xmr, fixed: 8}
- id: bchbtc
  code: 36
  base_unit: bch
  quote_unit: btc
  bid: {fee: 0, currency: btc, fixed: 8}
  ask: {fee: 0, currency: bch, fixed: 8}
- id: repbtc
  code: 37
  base_unit: rep
  quote_unit: btc
  bid: {fee: 0, currency: btc, fixed: 8}
  ask: {fee: 0, currency: rep, fixed: 8}
- id: btceth
  code: 18
  #name: BTC/EUR      # default name
  base_unit: btc
  quote_unit: eth
  #price_group_fixed: 1 # aggregate price levels in orderbook
  bid: {fee: 0, currency: eth, fixed: 2}
  ask: {fee: 0, currency: btc, fixed: 4}
  sort_order: 1
  #visible: false     # default to true
- id: ltceth
  code: 19
  base_unit: ltc
  quote_unit: inr
  bid: {fee: 0, currency: eth, fixed: 8}
  ask: {fee: 0, currency: ltc, fixed: 8}
- id: dasheth
  code: 20
  base_unit: dash
  quote_unit: eth
  bid: {fee: 0, currency: eth, fixed: 8}
  ask: {fee: 0, currency: dash, fixed: 8}
- id: zeceth
  code: 23
  base_unit: zec
  quote_unit: eth
  bid: {fee: 0, currency: eth, fixed: 8}
  ask: {fee: 0, currency: zec, fixed: 8}
- id: xrpeth
  code: 38
  base_unit: xrp
  quote_unit: eth
  bid: {fee: 0, currency: eth, fixed: 8}
  ask: {fee: 0, currency: xrp, fixed: 8}
- id: ppceth
  code: 39
  base_unit: ppc
  quote_unit: eth
  bid: {fee: 0, currency: eth, fixed: 8}
  ask: {fee: 0, currency: ppc, fixed: 8}
- id: nmceth
  code: 40
  base_unit: nmc
  quote_unit: eth
  bid: {fee: 0, currency: eth, fixed: 8}
  ask: {fee: 0, currency: nmc, fixed: 8}
- id: xmreth
  code: 41
  base_unit: xmr
  quote_unit: eth
  bid: {fee: 0, currency: eth, fixed: 8}
  ask: {fee: 0, currency: xmr, fixed: 8}
- id: bcheth
  code: 42
  base_unit: bch
  quote_unit: eth
  bid: {fee: 0, currency: eth, fixed: 8}
  ask: {fee: 0, currency: bch, fixed: 8}
- id: repeth
  code: 43
  base_unit: rep
  quote_unit: eth
  bid: {fee: 0, currency: eth, fixed: 8}
  ask: {fee: 0, currency: rep, fixed: 8}
- id: btcbch
  code: 24
  #name: BTC/EUR      # default name
  base_unit: btc
  quote_unit: bch
  #price_group_fixed: 1 # aggregate price levels in orderbook
  bid: {fee: 0, currency: bch, fixed: 2}
  ask: {fee: 0, currency: btc, fixed: 4}
  sort_order: 1
  #visible: false     # default to true
- id: ltcbch
  code: 25
  base_unit: ltc
  quote_unit: bch
  bid: {fee: 0, currency: bch, fixed: 8}
  ask: {fee: 0, currency: ltc, fixed: 8}
# - id: ltcbtc
#   code: 4
#   base_unit: ltc
#   quote_unit: btc
#   bid: {fee: 0, currency: btc, fixed: 8}
#   ask: {fee: 0, currency: ltc, fixed: 8}
- id: dashbch
  code: 26
  base_unit: dash
  quote_unit: bch
  bid: {fee: 0, currency: bch, fixed: 8}
  ask: {fee: 0, currency: dash, fixed: 8}
- id: ethbch
  code: 27
  base_unit: eth
  quote_unit: bch
  bid: {fee: 0, currency: bch, fixed: 8}
  ask: {fee: 0, currency: eth, fixed: 8}
- id: zecbch
  code: 28
  base_unit: zec
  quote_unit: bch
  bid: {fee: 0, currency: bch, fixed: 8}
  ask: {fee: 0, currency: zec, fixed: 8}
- id: xrpbch
  code: 38
  base_unit: xrp
  quote_unit: bch
  bid: {fee: 0, currency: bch, fixed: 8}
  ask: {fee: 0, currency: xrp, fixed: 8}
- id: ppcbch
  code: 39
  base_unit: ppc
  quote_unit: bch
  bid: {fee: 0, currency: bch, fixed: 8}
  ask: {fee: 0, currency: ppc, fixed: 8}
- id: nmcbch
  code: 40
  base_unit: nmc
  quote_unit: bch
  bid: {fee: 0, currency: bch, fixed: 8}
  ask: {fee: 0, currency: nmc, fixed: 8}
- id: xmrbch
  code: 41
  base_unit: xmr
  quote_unit: bch
  bid: {fee: 0, currency: bch, fixed: 8}
  ask: {fee: 0, currency: xmr, fixed: 8}
- id: repbch
  code: 43
  base_unit: rep
  quote_unit: bch
  bid: {fee: 0, currency: bch, fixed: 8}
  ask: {fee: 0, currency: rep, fixed: 8}